import 'package:flutter/material.dart';
import 'package:json_stream_parser_demo/pages/live_chat_demo/chat_provider.dart';
import 'package:json_stream_parser_demo/pages/live_chat_demo/top_bar.dart';
import 'package:provider/provider.dart';
import 'package:responsive_framework/responsive_framework.dart';

class LiveChatDemoPage extends StatefulWidget {
  const LiveChatDemoPage({super.key});

  @override
  State<LiveChatDemoPage> createState() => _LiveChatDemoPageState();
}

class _LiveChatDemoPageState extends State<LiveChatDemoPage> {
  final messageController = TextEditingController();

  String modelProvider = "Google";
  String modelName = "gemini-2.5-flash";
  final _geminiKeyController = TextEditingController();
  final _groqKeyController = TextEditingController();
  String? _geminiApiKey;
  String? _groqApiKey;

  void _showSettingsModal(BuildContext passedContext) {
    showModalBottomSheet(
        context: passedContext,
        builder: (modalContext) => BottomSheet(
            onClosing: () {},
            builder: (context) => Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Column(
                    children: [
                      ListTile(
                        onTap: () {},
                        title: Text("Gemini API Key"),
                        subtitle: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                                "Paste your Gemini API Key here if you want to use Google's Gemini models for testing"),
                            TextField(
                              controller: _geminiKeyController,
                              onChanged: (text) =>
                                  setState(() => _geminiApiKey = text),
                            )
                          ],
                        ),
                      ),
                      ListTile(
                        onTap: () {},
                        title: Text("Groq API Key"),
                        subtitle: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                                "Paste your Groq API Key here if you want to use Groq's LLM AI API for testing"),
                            TextField(
                              controller: _groqKeyController,
                              onChanged: (text) =>
                                  setState(() => _groqApiKey = text),
                            )
                          ],
                        ),
                      ),
                      ListenableBuilder(
                        listenable: passedContext.read<ChatProvider>(),
                        builder: (context, child) {
                          final chatProvider =
                              passedContext.read<ChatProvider>();
                          return SwitchListTile(
                            title: Text("Show Raw JSON"),
                            subtitle: Text(
                                "Display the raw JSON response being generated by the model"),
                            value: chatProvider.showRawJson,
                            onChanged: (value) {
                              chatProvider.toggleRawJsonDisplay();
                            },
                          );
                        },
                      ),
                      Spacer(),
                      Text('These are automatically saved and applied.')
                    ],
                  ),
                )));
  }

  void _showModelSelectionModal() {
    showModalBottomSheet(
        context: context,
        builder: (context) => BottomSheet(
            onClosing: () {},
            builder: (context) => Column(
                  children: models.keys
                      .map((modelProviderItem) => ExpansionTile(
                            title: Text(modelProviderItem),
                            children: models[modelProviderItem]!
                                .map((modelNameItem) => ListTile(
                                      title: Text(modelNameItem),
                                      onTap: () => setState(() {
                                        modelProvider = modelProviderItem;
                                        modelName = modelNameItem;
                                      }),
                                    ))
                                .toList(),
                          ))
                      .toList(),
                )));
  }

  void _onSubmitMessage(BuildContext context) {
    final message = messageController.text;
    if (message.isEmpty) return;

    if (_geminiApiKey != null || _groqApiKey != null) {
      context.read<ChatProvider>().sendMessage(
          message: message,
          modelProvider: modelProvider,
          modelName: modelName,
          geminiApiKey: _geminiApiKey,
          groqApiKey: _groqApiKey);
      messageController.clear();
    }
  }

  @override
  Widget build(BuildContext context) {
    final isMobile = ResponsiveBreakpoints.of(context).isMobile;

    return ChangeNotifierProvider(
      create: (context) => ChatProvider(),
      builder: (context, widget) => Center(
        child: Column(
          children: [
            SizedBox(
              width: isMobile ? double.infinity : 600,
              child: Row(
                children: [
                  Text(
                    'Live Chat Demo',
                    style: isMobile
                        ? Theme.of(context).textTheme.headlineSmall
                        : Theme.of(context).textTheme.headlineMedium,
                  ),
                  Spacer(),
                  IconButton(
                      onPressed: () => _showSettingsModal(context),
                      icon: Icon(Icons.settings))
                ],
              ),
            ),
            Expanded(
              child: SizedBox(
                  width: isMobile ? double.infinity : 600,
                  child: Card(
                    child: Column(
                      children: [
                        TopBar(),
                        Expanded(child: Consumer<ChatProvider>(
                          builder: (context, chatProvider, _) {
                            return ListView.builder(
                              padding: EdgeInsets.symmetric(
                                  horizontal: isMobile ? 4 : 16, vertical: 8),
                              itemCount: chatProvider.messageWidgets.length,
                              itemBuilder: (context, index) {
                                return chatProvider.messageWidgets[index];
                              },
                            );
                          },
                        )),
                        Consumer<ChatProvider>(
                          builder: (context, chatProvider, _) {
                            if (chatProvider.showRawJson &&
                                chatProvider.currentRawJson != null) {
                              return Container(
                                constraints: BoxConstraints(
                                  maxHeight: isMobile ? 150 : 200,
                                ),
                                padding: EdgeInsets.all(isMobile ? 4.0 : 8.0),
                                child: Card(
                                  color: Colors.black87,
                                  child: SingleChildScrollView(
                                    padding: EdgeInsets.all(8.0),
                                    child: SelectableText(
                                      chatProvider.currentRawJson ?? '',
                                      style: TextStyle(
                                        fontFamily: 'monospace',
                                        fontSize: 10,
                                        color: Colors.greenAccent,
                                      ),
                                    ),
                                  ),
                                ),
                              );
                            }
                            return SizedBox.shrink();
                          },
                        ),
                        Padding(
                          padding: EdgeInsets.all(isMobile ? 4.0 : 8.0),
                          child: SizedBox(
                            width: double.infinity,
                            height: isMobile ? 100 : 120,
                            child: Card(
                              color: Theme.of(context)
                                  .colorScheme
                                  .secondaryContainer,
                              child: Padding(
                                padding: EdgeInsets.all(isMobile ? 4.0 : 8.0),
                                child: Column(
                                  children: [
                                    Row(
                                      children: [
                                        Expanded(
                                          child: TextField(
                                            enabled: _geminiApiKey != null ||
                                                _groqApiKey != null,
                                            onSubmitted: Provider.of<
                                                        ChatProvider>(context)
                                                    .isGenerating
                                                ? null
                                                : (_) =>
                                                    _onSubmitMessage(context),
                                            controller: messageController,
                                            decoration: InputDecoration(
                                                border: InputBorder.none,
                                                hintText: _geminiKeyController
                                                            .text.isEmpty &&
                                                        _groqKeyController
                                                            .text.isEmpty
                                                    ? 'Add at least one API key to send a message'
                                                    : 'Type your message here'),
                                            style: TextStyle(
                                                fontSize: isMobile ? 14 : 16),
                                          ),
                                        ),
                                        IconButton.filled(
                                            onPressed: Provider.of<
                                                        ChatProvider>(context)
                                                    .isGenerating
                                                ? null
                                                : () =>
                                                    _onSubmitMessage(context),
                                            icon: Icon(Icons.arrow_upward))
                                      ],
                                    ),
                                    Spacer(),
                                    Row(
                                      children: [
                                        Expanded(
                                          child: TextButton(
                                              onPressed:
                                                  _showModelSelectionModal,
                                              child: Text(
                                                modelName,
                                                style: TextStyle(
                                                    fontSize:
                                                        isMobile ? 11 : 14),
                                                overflow: TextOverflow.ellipsis,
                                              )),
                                        ),
                                      ],
                                    )
                                  ],
                                ),
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  )),
            ),
            SizedBox(height: isMobile ? 60 : 40),
          ],
        ),
      ),
    );
  }
}
