import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:json_stream_parser/classes/json_stream_parser.dart';
import 'package:json_stream_parser/json_stream_parser.dart';

class NoteWidgetHandler with ChangeNotifier {
  String get exampleJson => jsonEncode({
    'notes': [
      {
        'type': 'note',
        'title': 'Welcome to the JsonStreamParser demo!',
        'content':
            'In this demo, we will show how to use the JsonStreamParser to parse JSON being generated by LLMs live!',
      },
      {
        'type': 'checklist',
        'title': 'Features',
        'items': [
          {'text': 'Parse JSON streams', 'checked': true},
          {'text': 'Handle large JSON data', 'checked': false},
          {'text': 'Integrate with LLMs', 'checked': true},
        ],
      },
      {
        'type': 'note',
        'title': 'Get Started',
        'content':
            'To get started, simply run the demo and observe how JSON data is parsed in real-time.',
      },
    ],
  });

  final List<Widget> noteWidgets = [];

  void runDemo() {
    // Simulate streaming JSON data for this demo
    final stream = streamTextInChunks(
      text: exampleJson,
      chunkSize: 5,
      interval: Durations.short4,
    ).asBroadcastStream();

    // Create a JsonStreamParser instance
    final parser = JsonStreamParser(stream);

    // Listen for parsed JSON objects and handle new elements
    // Here we are interested in the 'notes' array, which contains multiple note objects as Maps
    parser.getListProperty<Map>(
      'notes',
      onElement: (propertyStream, index) async {
        // TODO: The type param does not seem to enforcing that property stream is of type map
        final mapPropertyStream = propertyStream as MapPropertyStream;

        // await the type of note first before doing anything
        final type = await mapPropertyStream.getStringProperty('type').future;
      },
    );
  }
}
